Numpy

In [2]:
#Declare a list
list1=[1,2,3,4,5]
import numpy as np
arr=np.array(list1)
print(arr)
print(type(arr))
#All the data in the list should be of the same datatype

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
list2=[[1,2,3],[4,5,6],[7,8,9]]
matrix=np.array(list2)
print(matrix)

matrice=np.arange(1,10)
matrice.resize(3,3)
print(matrice)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
matrix=np.arange(11,38,3).reshape(3,3)
print(matrix)

[[11 14 17]
 [20 23 26]
 [29 32 35]]


In [5]:
#lenspace takes standard deviation too, +quantity of data elements to be print
matrice=np.linspace(0,20,21).reshape(3,7)
print(matrice)
type(matrice[0][0])

[[ 0.  1.  2.  3.  4.  5.  6.]
 [ 7.  8.  9. 10. 11. 12. 13.]
 [14. 15. 16. 17. 18. 19. 20.]]


numpy.float64

In [6]:
matrice_3=np.ones([3,3])
matrice_3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
matrice_3=np.zeros([3,3])
type(matrice_3[0][0])
#By default the data created is floating point

numpy.float64

In [8]:
matrice_3=np.eye(3)
print(matrice_3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
npa_5=np.arange(1,9)
npa_6=np.arange(0,8)
print(npa_5,npa_6)
npa_7=npa_6/npa_5
npa_8=npa_5**npa_6
#print(npa_7)
print(npa_8)
#In case they have same length they can be added

[1 2 3 4 5 6 7 8] [0 1 2 3 4 5 6 7]
[      1       2       9      64     625    7776  117649 2097152]


In [10]:
np1=np.arange(0,9).reshape(3,3)
np2=np.arange(2,11).reshape(3,3)
np3=np1/np2
print(np3)
#here only the corresponding elements are multiplied
np3=np1*np2
print(np3)

#If we put resize instead of reshape we will get error

[[0.         0.33333333 0.5       ]
 [0.6        0.66666667 0.71428571]
 [0.75       0.77777778 0.8       ]]
[[ 0  3  8]
 [15 24 35]
 [48 63 80]]


In [11]:
np1=np.arange(0,9).reshape(3,3)
np2=np.arange(2,11).reshape(3,3)
np_3=np.matmul(np1,np2)
np_3

array([[ 21,  24,  27],
       [ 66,  78,  90],
       [111, 132, 153]])

In [12]:
print(np_3[np_3>25])
#   But the shape is lost
#Printing the elments of matrix based on a condition

[ 27  66  78  90 111 132 153]


In [13]:
print(np1[1:2,1:3]) #retriving a portion of the matrix

[[4 5]]


In [14]:
np1[1:2,1:3]=0.4
print(np1)
#here all the elments are int therefore the value change to int

[[0 1 2]
 [3 0 0]
 [6 7 8]]


In [15]:
matrice=np.arange(0,25).reshape(5,5)
sub_mat=matrice[0:3,3:5]
sub_mat[:]=4
print(sub_mat)
print(matrice)
#The main matrice also gets changed as we are not making a copy

[[4 4]
 [4 4]
 [4 4]]
[[ 0  1  2  4  4]
 [ 5  6  7  4  4]
 [10 11 12  4  4]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [16]:
matrice=np.arange(0,25).reshape(5,5)
sub_mat=matrice[0:3,3:5].copy()
sub_mat[:]=4
print(sub_mat)
print(matrice)

[[4 4]
 [4 4]
 [4 4]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


Pandas

In [17]:
import pandas as pd
score=[10,20,30,40]
y=pd.Series(data=score,index=["a","b","c","d"]) #pretty much like enumerate function
#we are associating a index to a list
print(y)
y["a"] #We can retrive it based on thr index value

a    10
b    20
c    30
d    40
dtype: int64


10

In [18]:
import pandas as pd
score=[[10,20],[30,40]]
y=pd.Series(data=score,index=["a","b"]) #pretty much like enumerate function
#we are associating a index to a list
print(y)
y["a"] #We can retrive it based on thr index value

a    [10, 20]
b    [30, 40]
dtype: object


[10, 20]

In [19]:
#creating a data frame:
#series is a single column and data frams is multiple column
#key: column name, value =list of values
data={"roll_no":[1,2,3,4],"names":["A","B","C","D"],"marks":[90,93,99,97]}
data=pd.DataFrame(data,index=["a","b","c","d"])
print(data)

   roll_no names  marks
a        1     A     90
b        2     B     93
c        3     C     99
d        4     D     97


In [20]:
print(data.loc["a":"c"])

   roll_no names  marks
a        1     A     90
b        2     B     93
c        3     C     99


In [29]:
print(data.iloc[0:2,0:1])
#First 2 rows ,first column

   roll_no
0        1
1        2


In [22]:
data={"roll_no":[1,2,3,4],"names":["A","B","C","D"],"marks":[90,93,99,97]}
data=pd.DataFrame(data)
print(data.loc[0:2])

   roll_no names  marks
0        1     A     90
1        2     B     93
2        3     C     99
