In [4]:
from ultralytics import YOLO

In [7]:
trained_model = YOLO("C:/Users/Biancaa. R/Downloads/banana_ripe/runs/classify/train/weights/last.pt")

In [37]:
# import h5py
# f = h5py.File('my_model.h5', "r")
#out = trained_model.predict(list(uploaded.keys())[0],save=True)
from ultralytics import YOLO
import cv2
import numpy as np

# Define path to the image file
#source = 'C:/Users/Biancaa. R/Downloads/banana_ripe/runs/classify/train2/train_batch1.jpg'
source="C://Users//Biancaa. R//Downloads//banana_ripe//istockphoto-539370180-612x612.jpg"

# Run inference on the source
results = trained_model(source)  # list of Results objects
results[0].show()
annotated_frame = results[0].plot()
print(annotated_frame)

# # Convert PIL image to NumPy array
# annotated_frame_np = cv2.cvtColor(np.array(annotated_frame), cv2.COLOR_RGB2BGR)

# # Display annotated frame
# cv2.imshow("YOLOv5 Inference", annotated_frame_np)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

# import PIL
# img=PIL.Image.fromarray(annotated_frame)
# cv2.imshow("YOLOv8 Inference", img[1])
# # View results
# for r in results:
#     print(r.obb)  # print the Boxes object containing the detection bounding boxes


image 1/1 C:\Users\Biancaa. R\Downloads\banana_ripe\istockphoto-539370180-612x612.jpg: 224x224 rotten 0.98, overripe 0.02, ripe 0.00, unripe 0.00, 13.0ms
Speed: 4.0ms preprocess, 13.0ms inference, 0.0ms postprocess per image at shape (1, 3, 224, 224)
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
